--- #YAML:1.0
name:               MojoX-Log-Log4perl
version:            0.01
abstract:           Log::Log4perl logging for Mojo/Mojolicious
author:
    - Breno G. de Oliveira <garu@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Log4perl:  0
    Mojo:           0
    Test::More:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
